"""Builds the companion Kaggle notebook: the actual data-simulation source
code as runnable cells, a quick demo run of each script, and a look at the
full published datasets. Run this, then `kaggle kernels push` the output."""

import nbformat as nbf

HERE_PLANT_SIM = open("plant_simulator.py").read()
HERE_SCHEDULED = open("scheduled_data_generator.py").read()

nb = nbf.v4.new_notebook()
nb["metadata"] = {
    "kernelspec": {"name": "python3", "display_name": "Python 3", "language": "python"},
    "language_info": {"name": "python", "version": "3.12"},
}
cells = []


def md(text):
    cells.append(nbf.v4.new_markdown_cell(text))


def code(text):
    cells.append(nbf.v4.new_code_cell(text))


md("""\
# SWaT Digital Twin: the simulator that generates this dataset

This notebook is the actual source code behind [SWaT Digital Twin: Faults and Anomalies](https://www.kaggle.com/datasets/ariadaikalam/fyp-ml-dataset), the dataset attached to this kernel.

It's used throughout [Intelligent SCADA System using GenAI](https://github.com/ari-adaikalam/Intelligent-SCADA-System-using-GenAI), a project that turns a real water treatment baseline (the [SWaT dataset](https://www.kaggle.com/datasets/vishala28/swat-dataset-secure-water-treatment-system)) into a physics-based digital twin: components wear down, fault, and recover, with realistic sensor and motor signatures, because the real dataset has almost no fault data to train or demo against directly.

Two scripts, same physics engine, different purpose:

| Script | Purpose |
|---|---|
| `plant_simulator.py` | Realistic, randomly timed plant behavior. This is what feeds the live dashboard, ML predictions, and chatbot in the deployed app. |
| `scheduled_data_generator.py` | Same physics, but every component and fault type is scheduled to appear a guaranteed number of times. This is what the ML models train on. |

Both are reproduced here in full, followed by a quick demo run of each (a few hours of simulated time, so this kernel finishes fast), and then a look at the full datasets this project actually publishes and uses, which were generated by running these same scripts at full scale (200 days / full event schedule).""")

md("## Setup: point the scripts at the attached dataset's baseline CSV")

code("""\
import subprocess
print(subprocess.run(["find", "/kaggle/input", "-maxdepth", "3"], capture_output=True, text=True).stdout)
""")

code("""\
%%writefile paths.py
\"\"\"Adapted for this notebook: points at the attached Kaggle dataset's
clean_1.csv instead of a local file, everything else is identical to the
paths.py in the project's data-simulation/ folder.\"\"\"

from pathlib import Path

_candidates = list(Path("/kaggle/input").rglob("clean_1.csv"))
if not _candidates:
    raise FileNotFoundError(
        "Could not find clean_1.csv under /kaggle/input. "
        "Check that the fyp-ml-dataset dataset is attached to this notebook."
    )
RAW_BASELINE_CSV = _candidates[0]

OUTPUT_DIR = Path("/kaggle/working/output")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

PLANT_SIMULATION_FILE = OUTPUT_DIR / "plant_simulation_demo.csv"
TRAINING_DATA_FILE = OUTPUT_DIR / "training_data_demo.csv"
""")

md("## Part 1: `plant_simulator.py`\n\nThe realistic, randomly timed simulator. Full source, unmodified from the project repository.")

code(f"%%writefile plant_simulator.py\n{HERE_PLANT_SIM}")

md("## Part 2: `scheduled_data_generator.py`\n\nThe coverage-guaranteed training data generator. Full source, unmodified from the project repository.")

code(f"%%writefile scheduled_data_generator.py\n{HERE_SCHEDULED}")

md("""\
## Quick demo run

The published dataset uses a 200-day run for `plant_simulator.py` and the full event schedule (5 degradation cycles per component, 120 anomaly episodes per component/type pair) for `scheduled_data_generator.py`. That takes hours. Here's a short run of each instead, just to show the pipeline actually works end to end in this kernel.""")

code("""\
!timeout 180 python plant_simulator.py --duration-days 1
""")

code("""\
import pandas as pd
import matplotlib.pyplot as plt

demo = pd.read_csv("output/plant_simulation_demo.csv", parse_dates=["timestamp"])
print(demo.shape)
print(demo["system_status"].value_counts())

fig, axes = plt.subplots(2, 1, figsize=(12, 6), sharex=True)
axes[0].plot(demo["timestamp"], demo["expected_H_P101"])
axes[0].set_ylabel("P101 health")
axes[1].plot(demo["timestamp"], demo["true_FIT101"])
axes[1].set_ylabel("FIT101 flow")
axes[1].set_xlabel("time")
plt.tight_layout()
plt.show()
""")

md("""\
For the scheduled generator, patch the coverage targets and wear/fault durations down before running so this finishes in well under a minute (the published `training_data.csv` uses the real values: 5 cycles per component, 120 anomaly episodes per type, real wear rates, 8 to 15 hour faults). A DEGRADING episode normally runs until health crosses a threshold, which at real wear rates takes tens of simulated hours per component, that's the part that needs shrinking most for a quick demo.""")

code("""\
import re

src = open("scheduled_data_generator.py").read()
src = src.replace("CYCLES_PER_COMPONENT = 5", "CYCLES_PER_COMPONENT = 1")
src = src.replace("ANOMALY_EPISODES_PER_TYPE = 120", "ANOMALY_EPISODES_PER_TYPE = 2")
# Real wear rates take tens of simulated hours to reach a fault threshold.
# Speed that up for the demo so all 10 components can fault in seconds, not hours.
src = re.sub(r"'accel_wear_per_hour': \\([\\d.]+, [\\d.]+\\)", "'accel_wear_per_hour': (50.0, 80.0)", src)
src = src.replace("FAULT_DURATION_HOURS_RANGE = (8, 15)", "FAULT_DURATION_HOURS_RANGE = (0.05, 0.1)")
open("scheduled_data_generator.py", "w").write(src)
""")

code("""\
!timeout 180 python scheduled_data_generator.py
""")

code("""\
scheduled_demo = pd.read_csv("output/training_data_demo.csv")
print(scheduled_demo.shape)
print(scheduled_demo[["is_degrading", "is_faulted", "is_anomaly"]].sum())
""")

md("""\
## The full published datasets

The cells above prove the pipeline works. What follows is the actual data this project runs on, generated by these same scripts at full scale and attached to this kernel as the dataset.""")

code("""\
from paths import RAW_BASELINE_CSV

input_dir = RAW_BASELINE_CSV.parent
train = pd.read_csv(input_dir / "training_data.csv")
sim = pd.read_csv(input_dir / "plant_simulation.csv")

print("training_data.csv:", train.shape)
print("plant_simulation.csv:", sim.shape)

print(train["system_status"].value_counts())
print(sim["system_status"].value_counts())
""")

code("""\
# A full degradation-to-fault episode on P101, from the training data
p101 = train[train["degrading_component"].eq("P101") | train["faulted_component"].eq("P101")]
if len(p101) > 0:
    fig, ax = plt.subplots(figsize=(12, 4))
    ax.plot(p101["expected_H_P101"].reset_index(drop=True))
    ax.set_title("P101 health through a degradation episode (training_data.csv)")
    ax.set_ylabel("health")
    ax.set_xlabel("row")
    plt.show()
""")

md("""\
## Where the models trained on this data live

See [ml-training/](https://github.com/ari-adaikalam/Intelligent-SCADA-System-using-GenAI/tree/main/ml-training) in the project repository for the 3-stage pipeline (anomaly detection, state classification, component identification) trained on `training_data.csv` and validated against the held-out `plant_simulation.csv`.""")

nb["cells"] = cells

with open("digital_twin_notebook.ipynb", "w") as f:
    nbf.write(nb, f)

print(f"Wrote digital_twin_notebook.ipynb with {len(cells)} cells")
