using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace SwatDashboard.Models
{
    // ========================================================================
    // REQUEST MODELS (from frontend to backend)
    // ========================================================================
    
    /// <summary>
    /// Request model for sending a chat message
    /// </summary>
    public class ChatRequest
    {
        /// <summary>
        /// Unique session identifier (generated by frontend)
        /// </summary>
        public string SessionId { get; set; } = string.Empty;
        
        /// <summary>
        /// User's message text
        /// </summary>
        public string Message { get; set; } = string.Empty;
        
        /// <summary>
        /// Whether to include real-time data in the request
        /// </summary>
        public bool IncludeRealtime { get; set; }
    }
    
    // ========================================================================
    // RESPONSE MODELS (from backend to frontend)
    // ========================================================================
    
    /// <summary>
    /// Response model for chat messages
    /// </summary>
    public class ChatResponse
    {
        /// <summary>
        /// Success indicator
        /// </summary>
        public bool Success { get; set; } = true;
        
        /// <summary>
        /// Bot's text response
        /// </summary>
        public string Text { get; set; } = string.Empty;
        
        /// <summary>
        /// Chart.js configuration (if visualization needed)
        /// </summary>
        public object? ChartConfig { get; set; }
        
        /// <summary>
        /// Download links for generated reports
        /// </summary>
        public Dictionary<string, string>? DownloadLinks { get; set; }
        
        /// <summary>
        /// ML insights (if ML analysis was performed)
        /// </summary>
        public MlInsights? MlInsights { get; set; }
        
        /// <summary>
        /// Error message (if Success = false)
        /// </summary>
        public string? Error { get; set; }
        
        /// <summary>
        /// Additional metadata
        /// </summary>
        public ChatMetadata? Metadata { get; set; }
    }
    
    /// <summary>
    /// ML analysis insights
    /// </summary>
    public class MlInsights
    {
        public bool IsAnomaly { get; set; }
        public string State { get; set; } = "NORMAL";
        public string? FaultyComponent { get; set; }
        public double Confidence { get; set; }
        public List<string> Recommendations { get; set; } = new();
    }
    
    /// <summary>
    /// Response metadata
    /// </summary>
    public class ChatMetadata
    {
        public string? SqlQuery { get; set; }
        public int? RowCount { get; set; }
        public double ProcessingTimeMs { get; set; }
    }
    
    // ========================================================================
    // SESSION MANAGEMENT
    // ========================================================================
    
    /// <summary>
    /// Represents a chat session with conversation history
    /// </summary>
    public class ChatSession
    {
        /// <summary>
        /// Session creation time
        /// </summary>
        public DateTime CreatedAt { get; }
        
        /// <summary>
        /// Last activity timestamp
        /// </summary>
        public DateTime LastActivity { get; private set; }
        
        /// <summary>
        /// Conversation history (messages exchanged)
        /// </summary>
        public List<ChatMessage> ConversationHistory { get; }
        
        /// <summary>
        /// Constructor
        /// </summary>
        public ChatSession()
        {
            CreatedAt = DateTime.UtcNow;
            LastActivity = DateTime.UtcNow;
            ConversationHistory = new List<ChatMessage>();
        }
        
        /// <summary>
        /// Add a message pair to history
        /// </summary>
        public void AddMessage(string userMessage, string botResponse)
        {
            ConversationHistory.Add(new ChatMessage
            {
                Role = "user",
                Content = userMessage,
                Timestamp = DateTime.UtcNow
            });
            
            ConversationHistory.Add(new ChatMessage
            {
                Role = "assistant",
                Content = botResponse,
                Timestamp = DateTime.UtcNow
            });
            
            LastActivity = DateTime.UtcNow;
        }
        
        /// <summary>
        /// Check if session has expired (2 hours of inactivity)
        /// </summary>
        public bool IsExpired => (DateTime.UtcNow - LastActivity).TotalHours > 2;
        
        /// <summary>
        /// Get recent conversation history (for context)
        /// </summary>
        public List<ChatMessage> GetRecentHistory(int maxMessages = 10)
        {
            var count = Math.Min(maxMessages, ConversationHistory.Count);
            var startIndex = Math.Max(0, ConversationHistory.Count - count);
            return ConversationHistory.GetRange(startIndex, count);
        }
    }
    
    /// <summary>
    /// Individual chat message
    /// </summary>
    public class ChatMessage
    {
        public string Role { get; set; } = string.Empty; // "user" or "assistant"
        public string Content { get; set; } = string.Empty;
        public DateTime Timestamp { get; set; }
    }
    
    // ========================================================================
    // PYTHON RAG API MODELS (for communication with RAG service)
    // ========================================================================
    
    /// <summary>
    /// Request payload sent to Python RAG API
    /// </summary>
    

public class RagApiRequest
    {
        [JsonPropertyName("sessionId")]
        public string SessionId { get; set; } = string.Empty;

        [JsonPropertyName("message")]
        public string Message { get; set; } = string.Empty;

        [JsonPropertyName("conversationHistory")]
        public object ConversationHistory { get; set; } = new List<object>();

        [JsonPropertyName("realtimeData")]
        public object? RealtimeData { get; set; }

        [JsonPropertyName("databaseConnection")]
        public DatabaseConnectionInfo DatabaseConnection { get; set; } = new();
    }

    public class DatabaseConnectionInfo
    {
        [JsonPropertyName("server")]
        public string Server { get; set; } = string.Empty;

        [JsonPropertyName("database")]
        public string Database { get; set; } = string.Empty;

        [JsonPropertyName("username")]
        public string Username { get; set; } = string.Empty;

        [JsonPropertyName("password")]
        public string Password { get; set; } = string.Empty;
    }

    /// <summary>
    /// Response from Python RAG API
    /// </summary>
    public class RagApiResponse
    {
        public bool Success { get; set; }
        public string Text { get; set; } = string.Empty;
        public object? ChartConfig { get; set; }
        public Dictionary<string, string>? DownloadLinks { get; set; }
        public RagMlInsights? MlInsights { get; set; }
        public string? SqlQuery { get; set; }
        public int? RowCount { get; set; }
        public string? Error { get; set; }
    }
    
    /// <summary>
    /// ML insights from RAG API
    /// </summary>
    public class RagMlInsights
    {
        public bool IsAnomaly { get; set; }
        public string State { get; set; } = string.Empty;
        public string? FaultyComponent { get; set; }
        public double Confidence { get; set; }
        public List<string> Recommendations { get; set; } = new();
    }
    
    // ========================================================================
    // STATUS MODELS
    // ========================================================================
    
    /// <summary>
    /// Chat service health status
    /// </summary>
    public class ChatHealthStatus
    {
        public string Status { get; set; } = "unknown";
        public bool RagApiAvailable { get; set; }
        public bool MlApiAvailable { get; set; }
        public bool DatabaseAvailable { get; set; }
        public int ActiveSessions { get; set; }
        public DateTime CheckedAt { get; set; }
    }
}
